### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by SergeyBaikal** [Aciole-David/biovirushost2excel#1]
Hello Aciole-David!
I am getting the following error

```
python3 biovirushost2excel.py 
  File "biovirushost2excel.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

**Comment by Aciole-David** [comment]
Have you edited the script?

**Comment by SergeyBaikal** [comment]
Hi Aciole-David!
Sorry, I'm stupid) Everything works, great job! Thank you very much!!!
 
 The only drawback is the very slow work due to the online work of the script. Is it possible to do a search locally?
